export LC_ALL=en_US.utf8
export LANG=en_US.utf8
export PATH="$HOME/bin:$HOME/.go/bin:$PATH"
export TERM="xterm-256color"
export EDITOR="vim"
export TERMINAL=termite
export BROWSER=/home/fox/bin/open.sh
export GOPATH="/home/fox/.go"
export HISTSIZE=1000000
export SAVEHIST=1000000
export HISTFILE=~/.zsh_history
. /etc/profile.d/vte.sh
