# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

config.unbind('u')
config.unbind('d')
config.unbind('@')
config.unbind('q')

config.bind('<ctrl-d>', 'tab-close')
config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')
config.bind('F', 'hint all tab-bg')
config.bind('d', 'scroll-page 0 0.5')
config.bind('u', 'scroll-page 0 -0.5')
# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()
