#!/bin/sh


wlp_state="$(cat /sys/class/net/wl*/operstate)" \
eth_state="$(cat /sys/class/net/en*/operstate)"

ssid=$(nmcli c s --active | tail -n 1 | cut -d " " -f 1)

wlp_name="$(ls /sys/class/net | grep wl)"
eth_name="$(ls /sys/class/net | grep en)"


if [ "$eth_state" = "up" ]; then
        echo " $eth_name/$ssid"
        echo " $eth_name/$ssid"
        echo "#99CC99"
        exit 0
fi

if [ "$eth_state" = "down" ]; then
        echo " $eth_name/$ssid"
        echo " $eth_name/$ssid"
        echo "#F2777A"
        exit 0
fi

if [ "$eth_state" = "dormant" ]; then
        echo ""
        echo ""
        echo "#F99157"
        exit 0
fi
if [ "$wlp_state" = "up" ]; then
        echo " $wlp_name/$ssid"
        echo " $wlp_name/$ssid"
        echo "#99CC99"
        exit 0
fi

if [ "$wlp_state" = "down" ]; then
        echo " $wlp_name/$ssid"
        echo " $wlp_name/$ssid"
        echo "#F2777A"
        exit 0
fi

